# Generated by Django 5.2.12 on 2026-03-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="topics",
        ),
        migrations.AddField(
            model_name="product",
            name="materials",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of materials used in the product",
            ),
        ),
    ]
