# Generated by Django 5.2.12 on 2026-04-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_image_url_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="product",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="product",
            name="nutritional_information",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False, help_text="Show this category on the homepage"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_preservation_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="taste",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Very_Spicy", "Very Spicy"),
                    ("Medium_Spicy", "Medium Spicy"),
                    ("Mild_Spicy", "Mild Spicy"),
                    ("Sour", "Sour"),
                    ("Sweet", "Sweet"),
                    ("Sweet_Sour", "Sweet & Sour"),
                    ("Spicy_Sour", "Spicy & Sour"),
                    ("Spicy_Sweet", "Spicy & Sweet"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="key_ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.ingredient"
            ),
        ),
    ]
